### PR TITLE
fix: connection issues on Flatpak and Snap installations

### LINKED ISSUE #16: ConnectionException on Fedora 39
ConnectionException is thrown when connecting on Fedora 39. **This seems to persist even when Discord client is closed.**

### Reproducible example

```kt
fun main() {
    val client = RichClient(/* id */)
    client.connect()
}
```

### Stacktrace

```
Exception in thread "main" io.github.vyfor.kpresence.exception.ConnectionException
	at io.github.vyfor.kpresence.ipc.Connection$UnixConnection.open(Connection.kt:135)
	at io.github.vyfor.kpresence.ipc.Connection.open(Connection.kt:24)
	at io.github.vyfor.kpresence.RichClient.connect(RichClient.kt:53)
	at io.github.vyfor.kpresence.RichClient.connect$default(RichClient.kt:47)
	at io.github.pandier.MainKt.main(Main.kt:7)
	at io.github.pandier.MainKt.main(Main.kt)
```

Stacktrace of `exception` inside `ConnectionException`:

```
java.net.SocketException: No such file or directory
	at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
	at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:148)
	at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:144)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:851)
	at java.base/java.nio.channels.SocketChannel.open(SocketChannel.java:285)
	at io.github.vyfor.kpresence.ipc.Connection$UnixConnection.open(Connection.kt:130)
	at io.github.vyfor.kpresence.ipc.Connection.open(Connection.kt:24)
	at io.github.vyfor.kpresence.RichClient.connect(RichClient.kt:53)
	at io.github.vyfor.kpresence.RichClient.connect$default(RichClient.kt:47)
	at io.github.pandier.MainKt.main(Main.kt:9)
	at io.github.pandier.MainKt.main(Main.kt)
```

### Environment

- KPresence version: 0.6.0
- OS: Fedora 39

### PR DESCRIPTION
**Pull request by vyfor**
closes #16, #17

### CODE REVIEW

File: src/jvmMain/kotlin/io/github/vyfor/kpresence/ipc/Connection.kt [hunk 1]
```diff
@@ -118,21 +119,31 @@ actual class Connection {
...
-         getenv("TEMP")) ?:
-        "/tmp"
+      val dirs =
+        listOf("XDG_RUNTIME_DIR", "TMPDIR", "TMP", "TEMP")
+          .mapNotNull(::getenv)
+          .plus("/tmp")
+          .flatMap { base ->
+            listOf(
+              base,
+              "$base/app/com.discordapp.Discord",
```
Comment (limpid-kzonix) [inline src/jvmMain/kotlin/io/github/vyfor/kpresence/ipc/Connection.kt:129]: /run/user/1000/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-0
